version: "2"
services:
  app:
    depends_on:
      - db
    links:
      - db:mongodb
    container_name: gamebot_app
    build: "."
    restart: always
    ports:
      - "5000:5000"
  db:
    container_name: gamebot_db
    image: "mongo:2.4.14"
    restart: always
